Fix compile by disabling unit test.
The messaging widget test uses MessagingWidget API and fails to
link because that class is not exported:

CMakeFiles/messagingwidgettest.dir/messagingwidgettest.cpp.o: In function `MessagingWidgetTest::shouldHaveDefaultValues()':
/home/milian/projects/kf5/src/kde/kdepimlibs/akonadi-contact/src/editor/generalinfoeditor/autotests/messagingwidgettest.cpp:40: undefined reference to `Akonadi::MessagingWidget::MessagingWidget(QWidget*)'
/home/milian/projects/kf5/src/kde/kdepimlibs/akonadi-contact/src/editor/generalinfoeditor/autotests/messagingwidgettest.cpp:40: undefined reference to `Akonadi::MessagingWidget::~MessagingWidget()'
collect2: error: ld returned 1 exit status
akonadi-contact/src/editor/generalinfoeditor/autotests/CMakeFiles/messagingwidgettest.dir/build.make:120: recipe for target 'akonadi-contact/src/editor/generalinfoeditor/autotests/messagingwidgettest' failed

I hope it's OK that I push this hotfix to get it working again.

CCMAIL: montel@kde.org